# Generated by Django 6.0.1 on 2026-03-19 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetEditProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("add", "Add"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        default="update",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("drug", models.CharField(max_length=255)),
                ("target", models.CharField(max_length=255)),
                ("drug_class", models.CharField(blank=True, max_length=255)),
                ("activity", models.CharField(blank=True, max_length=255)),
                ("activity_recoded", models.CharField(blank=True, max_length=255)),
                ("ki_lower_nm", models.FloatField(blank=True, null=True)),
                ("ki_upper_nm", models.FloatField(blank=True, null=True)),
                ("modelled_ki_nm", models.FloatField(blank=True, null=True)),
                ("ki_is_range", models.BooleanField(default=False)),
                ("pKi", models.FloatField(blank=True, null=True)),
                ("citation", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("processing_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_dataset_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_dataset_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "can_approve_dataset_edit",
                        "Can approve/reject dataset edit proposals",
                    )
                ],
            },
        ),
    ]
