# Generated by Django 6.0.1 on 2026-03-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dataseteditproposal",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "can_propose_dataset_edit",
                        "Can create/update dataset edit proposals",
                    ),
                    (
                        "can_approve_dataset_edit",
                        "Can approve/reject dataset edit proposals",
                    ),
                ],
            },
        ),
    ]
